In [12]:
import model
import numpy as np

In [4]:
ds2 = model.DeepSpeech()

In [15]:
ds2.rnns[0].rnn.state_dict()[list(ds2.rnns[0].rnn.state_dict().keys())[0]].numpy()

array([[ 0.03268374, -0.02072847,  0.00023607, ..., -0.01638727,
        -0.01343331, -0.01063785],
       [ 0.00475388, -0.01591629,  0.03524786, ..., -0.02406869,
         0.02337616, -0.03605283],
       [ 0.02220825, -0.00687078,  0.02184571, ..., -0.01539167,
        -0.02830457,  0.02730836],
       ...,
       [-0.01024905, -0.01455793,  0.00716665, ...,  0.00952554,
         0.0304292 ,  0.03316211],
       [-0.00616149,  0.00077237, -0.01200251, ..., -0.02545009,
         0.01924526,  0.00332287],
       [-0.02903486, -0.02540605, -0.01490297, ...,  0.0231097 ,
        -0.00355718, -0.00535908]], dtype=float32)

In [16]:
a = ds2.rnns[0].rnn.state_dict()[list(ds2.rnns[0].rnn.state_dict().keys())[0]].numpy()

In [25]:
r,c = a.shape

In [30]:
np.split(a,4)

4

-0.015916288

In [141]:
x = np.arange(256)

In [142]:
x = x.reshape((16,16))

In [143]:
r,c = x.shape

In [144]:
x

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
         13,  14,  15],
       [ 16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,  28,
         29,  30,  31],
       [ 32,  33,  34,  35,  36,  37,  38,  39,  40,  41,  42,  43,  44,
         45,  46,  47],
       [ 48,  49,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,
         61,  62,  63],
       [ 64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,
         77,  78,  79],
       [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,
         93,  94,  95],
       [ 96,  97,  98,  99, 100, 101, 102, 103, 104, 105, 106, 107, 108,
        109, 110, 111],
       [112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124,
        125, 126, 127],
       [128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140,
        141, 142, 143],
       [144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
        157, 158, 159],
       [160, 161, 162, 163, 16

In [213]:
def get_blocks(x,size):
    l=[]
    r,c = x.shape
    for i in range(0,r,size):
        for j in range(0,c,size):
            l.append(x[i:i+size,j:j+size])
    return np.array(l)

In [146]:
z = get_blocks(x,4)

In [147]:
z

array([[[  0,   1,   2,   3],
        [ 16,  17,  18,  19],
        [ 32,  33,  34,  35],
        [ 48,  49,  50,  51]],

       [[  4,   5,   6,   7],
        [ 20,  21,  22,  23],
        [ 36,  37,  38,  39],
        [ 52,  53,  54,  55]],

       [[  8,   9,  10,  11],
        [ 24,  25,  26,  27],
        [ 40,  41,  42,  43],
        [ 56,  57,  58,  59]],

       [[ 12,  13,  14,  15],
        [ 28,  29,  30,  31],
        [ 44,  45,  46,  47],
        [ 60,  61,  62,  63]],

       [[ 64,  65,  66,  67],
        [ 80,  81,  82,  83],
        [ 96,  97,  98,  99],
        [112, 113, 114, 115]],

       [[ 68,  69,  70,  71],
        [ 84,  85,  86,  87],
        [100, 101, 102, 103],
        [116, 117, 118, 119]],

       [[ 72,  73,  74,  75],
        [ 88,  89,  90,  91],
        [104, 105, 106, 107],
        [120, 121, 122, 123]],

       [[ 76,  77,  78,  79],
        [ 92,  93,  94,  95],
        [108, 109, 110, 111],
        [124, 125, 126, 127]],

       [[128, 129, 130, 

In [148]:
y = [np.max(z[i]) for i in range(len(z))]

In [177]:
a = np.zeros(4)

In [179]:
a[1] = -1

In [180]:
a

array([ 0., -1.,  0.,  0.])

In [150]:
for i in range(len(y)):
    if (y[i]<120):
        z[i] = np.zeros(z[i].shape)

In [152]:
z

array([[[  0,   0,   0,   0],
        [  0,   0,   0,   0],
        [  0,   0,   0,   0],
        [  0,   0,   0,   0]],

       [[  0,   0,   0,   0],
        [  0,   0,   0,   0],
        [  0,   0,   0,   0],
        [  0,   0,   0,   0]],

       [[  0,   0,   0,   0],
        [  0,   0,   0,   0],
        [  0,   0,   0,   0],
        [  0,   0,   0,   0]],

       [[  0,   0,   0,   0],
        [  0,   0,   0,   0],
        [  0,   0,   0,   0],
        [  0,   0,   0,   0]],

       [[  0,   0,   0,   0],
        [  0,   0,   0,   0],
        [  0,   0,   0,   0],
        [  0,   0,   0,   0]],

       [[  0,   0,   0,   0],
        [  0,   0,   0,   0],
        [  0,   0,   0,   0],
        [  0,   0,   0,   0]],

       [[ 72,  73,  74,  75],
        [ 88,  89,  90,  91],
        [104, 105, 106, 107],
        [120, 121, 122, 123]],

       [[ 76,  77,  78,  79],
        [ 92,  93,  94,  95],
        [108, 109, 110, 111],
        [124, 125, 126, 127]],

       [[128, 129, 130, 

In [170]:
#has hardcoded params, can be changed later to add to training class
def get_threshold(x,block_size):
    #85% sparsity
    q = np.percentile(x,85)
    #based on heuristics in paper, change as you need
    theta = q*100*2/(2*(0.2*params.epochs-2)+3*(0.4*params.epochs-0.2*params.epochs))
    return theta*pow(block_size,0.25)
    

In [188]:
from collections import OrderedDict

In [189]:
new_state_dict = OrderedDict

In [227]:
wanted_weights = []
for k in ds2.state_dict().keys():
    if 'rnn' in k:
        wanted_weights.append(k)

In [228]:
new_state_dict = ds2.state_dict().copy()

In [229]:
def weight_prune(arr,threshold,size):
    blk_arr = get_blocks(arr,size)
    y = [np.max(blk_arr[i]) for i in range(len(blk_arr))]
    print(len(y))
    pruned_inds = np.abs(y) > threshold
    print(pruned_inds)
    '''for i in range(len(y)):
        reshaped_mask = np.full(blk_arr[i].shape,pruned_inds[i])'''
    try:
        r,c = arr.shape
        ctr = 0
        #print(len(reshaped_mask))
        for i in range(0,r,size):
            for j in range(0,c,size):
                #print(ctr)
                #print(blk_arr[0])
                #print(reshaped_mask)
                arr[i:i+size,j:j+size] = arr[i:i+size,j:j+size]*pruned_inds[ctr]
                ctr+=1
    except:
        return
for w in wanted_weights:
    print(w)
    weight_prune(new_state_dict[w].numpy(),0.01,4)

rnns.0.rnn.weight_ih_l0
129024
[False False False ...  True  True  True]
rnns.0.rnn.weight_hh_l0
147456
[ True  True  True ...  True  True  True]
rnns.0.rnn.weight_ih_l0_reverse
129024
[ True  True  True ...  True  True  True]
rnns.0.rnn.weight_hh_l0_reverse
147456
[ True  True  True ...  True  True  True]
rnns.1.rnn.weight_ih_l0
147456
[ True  True  True ...  True  True  True]
rnns.1.rnn.weight_hh_l0
147456
[ True  True  True ...  True  True  True]
rnns.1.rnn.weight_ih_l0_reverse
147456
[ True  True  True ...  True  True  True]
rnns.1.rnn.weight_hh_l0_reverse
147456
[ True  True  True ...  True  True  True]
rnns.2.rnn.weight_ih_l0
147456
[ True  True  True ...  True  True  True]
rnns.2.rnn.weight_hh_l0
147456
[ True  True  True ...  True  True  True]
rnns.2.rnn.weight_ih_l0_reverse
147456
[ True  True  True ...  True  True  True]
rnns.2.rnn.weight_hh_l0_reverse
147456
[ True  True  True ...  True  True  True]
rnns.3.rnn.weight_ih_l0
147456
[ True  True  True ...  True  True  True]
rnn

tensor([[ 0.0000, -0.0000,  0.0000,  ..., -0.0164, -0.0134, -0.0106],
        [ 0.0000, -0.0000,  0.0000,  ..., -0.0241,  0.0234, -0.0361],
        [ 0.0000, -0.0000,  0.0000,  ..., -0.0154, -0.0283,  0.0273],
        ...,
        [-0.0102, -0.0146,  0.0072,  ...,  0.0095,  0.0304,  0.0332],
        [-0.0062,  0.0008, -0.0120,  ..., -0.0255,  0.0192,  0.0033],
        [-0.0290, -0.0254, -0.0149,  ...,  0.0231, -0.0036, -0.0054]])

In [214]:
get_blocks(new_state_dict['rnns.0.rnn.weight_ih_l0'].numpy(),4)

array([[[ 0.        , -0.        ,  0.        , -0.        ],
        [ 0.        , -0.        ,  0.        , -0.        ],
        [ 0.        , -0.        ,  0.        ,  0.        ],
        [-0.        , -0.        , -0.        ,  0.        ]],

       [[ 0.        ,  0.        , -0.        , -0.        ],
        [ 0.        , -0.        , -0.        ,  0.        ],
        [-0.        ,  0.        ,  0.        , -0.        ],
        [ 0.        , -0.        , -0.        , -0.        ]],

       [[-0.        ,  0.        ,  0.        ,  0.        ],
        [-0.        ,  0.        ,  0.        ,  0.        ],
        [ 0.        , -0.        ,  0.        , -0.        ],
        [ 0.        ,  0.        , -0.        ,  0.        ]],

       ...,

       [[-0.00779252,  0.03134624, -0.01302069, -0.01870524],
        [ 0.02589906,  0.03574664, -0.01294108, -0.00104251],
        [-0.03145704,  0.02047625,  0.01766683,  0.02454479],
        [ 0.02867739,  0.02128186,  0.00302703,  0.